#ifndef GAME_CONSTANTS_H
#define GAME_CONSTANTS_H

#include <stdint.h>

#define MIN_PLANET_ID 0
#define MAX_PLANET_ID 65535

#define AREA_LENGTH 20000

// Read-only
#define ATTACKERS_SIZE 5
#define EXPLORERS_SIZE 2
#define COLLECTORS_SIZE 2
extern int8_t ATTACKERS[ATTACKERS_SIZE];
extern int8_t EXPLORERS[EXPLORERS_SIZE];
extern int8_t COLLECTORS[COLLECTORS_SIZE];

// Move
#define COLLECTORS_MAX_SPEED 1000
#define EXPLORERS_MAX_SPEED 2000
#define ATTACKERS_MAX_SPEED 3000

#define MAX_ANGLE 359

// Fire
#define FIRE_RANGE 5000

// RADAR
#define RADAR_RANGE 5000
enum RadarType { PLANET = 'P', SPACESHIP = 'S', BASE = 'B' };

#endif // GAME_CONSTANTS_H
